version: '1.0'
name: pr-pipeline
displayName: PRPipeline
triggers:
  trigger: auto
  pr:
    branches:
      include:
        - master
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@python
        name: build_python
        displayName: Python 构建
        pythonVersion: '3.9'
        commands:
          - python3 -m pip install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple
          - pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - pip3 install poetry
          - cd ./algorithm
          - python3 -m poetry install
          - python3 -m poetry run  python ./tests/test_binary_search.py
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
        strategy: {}
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
        dependsOn: build_python
